#!/bin/bash

# usage:  "$0" foo.srt 
# STDOUT is fixitplus-format JSON
#
# example of SRT format expected:
# 1 
# 00:00:00,000 --> 00:00:00,000
# SRT Captions File Generated by MXFplus
# 
# 2
# 00:01:39,533 --> 00:01:44,433
# [MUSIC PLAYING]
#
# lines with only numbers are discarded
# lines without any text are discarded

function smpte2secs {
   tcode=$(echo $1 | tr -dC '[0-9]:;\.') ;
   while [ "$(echo $tcode | tr -s ':' ' ' | wc -w | awk '{print $1}')" -lt 3 ];
   do 
	   tcode="0:$tcode";
   done
   echo "$tcode"':0:0:0:0' | tr -s ':;' ' ' | awk '{print "scale=2;"$1" * 3600 + "$2" * 60 + "$3" + ("$4"/30)"}' | bc
}


if [ "$#" != 1 -o ! -f "$1" -o "$(basename "$1" | sed 's#^.*\.##g')" != 'srt' ] ;
then 
	usage >&2;
	exit ;
fi

IFS=$'\n\r\b' ;

guid=$(basename "$1" .srt);
spid=0;
echo $(printf %s '{"id":"'$guid'","language":"en-US","parts":[' ; 
	for line in $( grep -v '^$\|^[0-9]*$' "$1" );
	do 
		spid=$[$spid+1];
		if [ -n "$(echo $line | grep ' --> ')" ];
		then 
			smpte_start=$(echo $line | awk -F' --> ' '{print $1}'); 
			smpte_end=$(echo $line | awk -F' --> ' '{print $2}');
			stime=$(smpte2secs "$smpte_start");
			etime=$(smpte2secs "$smpte_end");
			if [ "$spid" -gt 1 ];then printf %s '"},' ; fi; 
				echo '{"speaker_id":'"$spid"',"start_time": '$stime',"end_time": '$etime',"text": "';  
			else 
				echo $line | sed 's#"#\\&#g' | tr '\n' ' ';
			fi;
		done;echo '"}]}') | jq -r '.'